/********************************************************************************
 * Kitalive Source Materials.
 * Copyright (c) 2021 Kitalive Inc. All Rights Reserved.
 *
 * 定数クラス
 *
 ********************************************************************************
 * Date                Name             Reason for change
 ********************************************************************************
 * 2021/05/17          M.Kawasaki       New
 ********************************************************************************/
public class Constants {

    public static final String UPDATE_CYCLE_AUTO = 'auto';            // 自動更新
    public static final String UPDATE_CYCLE_3_MONTHS = '3Months';            // 3か月更新
    public static final String UPDATE_CYCLE_6_MONTHS = '6Months';            // 6か月更新
    public static final String UPDATE_CYCLE_12_MONTHS = '12Months';            // 12か月更新

    public static final String DETAIL_TYPE_INICIAL_COST = 'initialCost';            // 初期費用
    public static final String DETAIL_TYPE_MONTHLY_COST = 'monthlyCost';            // 月額費用
    public static final String DETAIL_TYPE_ANNUAL = 'annual';                       // 年払い
    public static final String DETAIL_TYPE_SPOT = 'spot';                           // スポット

    public static final String BILLING_START_MONTH = 'contractStartMonth';          // 契約開始月
    public static final String BILLING_START_NEXT_MONTH = 'contractStartNextMonth'; // 契約開始翌月
    public static final String BILLING_START_SPECIFIED_MONTH = 'specifiedMonth';    // 指定月

    public static final String TAX_TYPE_NO_TAX = 'noTax';                           // 非課税
    public static final String TAX_TYPE_10 = 'tax10';                               // 課税10%
}